# Directory to parse
source: ./sass

# Directory to build the styleguide
destination: ./styleguide

# Hologram theme
documentation_assets: ./bower_components/Cortana
custom_markdown: ./bower_components/Cortana/CortanaMarkdownRenderer.rb

# To have a custom index page build with your README.md
index: README

# List all css to include for the styleguide render examples (path from styleguide directory)
css_include:
  - '../stylesheets/styles.css'

# List all js to include for the styleguide render examples (path from styleguide directory)
js_include:
  - 'http://code.jquery.com/jquery-1.10.2.min.js'

dependencies:
  - ./images

# String who is used to split the category name and create category wrapper
name_scope: ' - '